// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct DrinkDTO: Codable {
    public var name: String?
    public var drink: String?
    public var amount: Double?
    public var timestamp: String?

    public init(name: String? = nil, drink: String? = nil, amount: Double? = nil, timestamp: String? = nil) {
        self.name = name
        self.drink = drink
        self.amount = amount
        self.timestamp = timestamp
    }
}

public struct ProfileDTO: Codable {
    public var name: UserDTO?
    public var drinks: [DrinkDTO]?

    public init(name: UserDTO? = nil, drinks: [DrinkDTO]? = nil) {
        self.name = name
        self.drinks = drinks
    }
}

public struct UserDTO: Codable {
    public var name: String?
    public var id: Double?

    public init(name: String? = nil, id: Double? = nil) {
        self.name = name
        self.id = id
    }
}

struct StringCodingKey: CodingKey, ExpressibleByStringLiteral {
    private let string: String
    private var int: Int?

    var stringValue: String { return string }

    init(string: String) {
        self.string = string
    }

    init?(stringValue: String) {
        self.string = stringValue
    }

    var intValue: Int? { return int }

    init?(intValue: Int) {
        self.string = String(describing: intValue)
        self.int = intValue
    }

    init(stringLiteral value: String) {
        self.string = value
    }
}
