// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get

extension Paths {
    public static var drinks: Drinks {
        Drinks(path: "/drinks")
    }

    public struct Drinks {
        /// Path: `/drinks`
        public let path: String

        /// Add a new drink to your Profile
        public func post(_ body: api.DrinkDTO) -> Request<Void> {
            .post(path, body: body)
        }
    }
}

extension Paths {
    public static var fetchProfile: FetchProfile {
        FetchProfile(path: "/fetchProfile")
    }

    public struct FetchProfile {
        /// Path: `/fetchProfile`
        public let path: String

        /// Fetch a profile to view the drink summary
        public var get: Request<api.ProfileDTO> {
            .get(path)
        }
    }
}

extension Paths {
    public static var getUsers: GetUsers {
        GetUsers(path: "/getUsers")
    }

    public struct GetUsers {
        /// Path: `/getUsers`
        public let path: String

        /// Fetch all Users
        public var get: Request<[api.UserDTO]> {
            .get(path)
        }
    }
}

extension Paths {
    public static var postUser: PostUser {
        PostUser(path: "/postUser")
    }

    public struct PostUser {
        /// Path: `/postUser`
        public let path: String

        /// Add a new User
        public var post: Request<[api.UserDTO]> {
            .post(path)
        }
    }
}

public enum Paths {}
